version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 7163:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_started
        restart: true
    ports:
      - 7164:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    stdin_open: true
    tty: true

  producer:
    build:
      context: ./receiver
      dockerfile: Dockerfile
    command: python /usr/src/app/faker.py
    volumes:
      - ./receiver:/usr/src/app
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      kafka:
        condition: service_started
        restart: true
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "7162:8000"
    depends_on:
      producer:
        condition: service_started
        restart: true
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7161:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true